name: Build Test

on:
  push:
    branches: [ main, Delta-Time-Fading ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install ESPHome
        run: pip install esphome
        
      - name: Compile ESPHome Test
        run: esphome compile tests/test.yaml
